### ISSUE TITLE
Incorrect TxLevel from "getTxLevelByPercentage"

### ISSUE THREAD

**Issue by Ashp116** [NordicID/nurapi_java_seektag_sample_android#1]
The function `NurUtils.getTxLevelByPercentage(nurApi, 45)` is returning an invalid TxLevel after  35%. Using this function gives values from 0-30, while the Tx_Levels goes from 0-19. 

Here is an image to show the Tx_Level when the percentage is at 0%.
![image](https://github.com/user-attachments/assets/0020c09b-a02f-43e0-9875-7c4f2a51ecee)

This is caused by the "txSteps" returning 30, while the txLevel goes till 19 (only having 20 steps).

**Comment by Ashp116** [comment]
If I just use the current function as is and set the TxLevel, I get this error; Indicating to an invalid txLevel.

Percentage used "0%"
![image](https://github.com/user-attachments/assets/15e81d40-a50f-4449-82ca-dd8b70a4711f)

**Comment by Buryyy** [comment]
Hi @Ashp116,

I’m having trouble replicating the issue you're experiencing. Could you please let me know which device you have tested this on? It seems that your device is recognizing 20 transmission steps only, although 'txSteps' says 30.

Debug with Nordic ID HH 85: 
![image](https://github.com/user-attachments/assets/df6eaa3e-f194-4ad7-956a-079726d647cd)

Thank you!

**Comment by Buryyy** [comment]
I have fixed the second error that occurred, the getTxLevelByPercentage(...) given the value of 0. The new JAR library can be found here: [v1.1 release](https://github.com/NordicID/nurapi_java_seektag_sample_android/releases/tag/1.1).

If you are using this repository, you can fetch and pull to get the latest library.

**Comment by Ashp116** [comment]
Hi @Buryyy,

Thank you for the fix! I updated NurUtils and it seems to not give me any errors.
